#%% 
SUPPORTED_TTS_LANGUAGES = { #incorporate with auto detection, add piper languages for each
    "en": "English",
    "es": "Spanish",
    "ht": "Haitian Creole",
    "pt": "Portuguese",
    "fr": "French",
    "it": "Italian",
    "de": "German",
    "ru": "Russian",
    "zh": "Chinese",
    "ja": "Japanese",
    "ko": "Korean",
    "ar": "Arabic",
    "hi": "Hindi",
    "tr": "Turkish",
    "he": "Hebrew",
}

#%% 
ONES = {
    0: "zero",
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
}

TEENS = {
    10: "ten",
    11: "eleven",
    12: "twelve",
    13: "thir teen",
    14: "four teen",
    15: "fif teen",
    16: "six teen",
    17: "seven teen",
    18: "eight teen",
    19: "nine teen",
}

TENS = {
    20: "twen tee",
    30: "thir tee",
    40: "for tee",
    50: "fif tee",
    60: "six tee",
    70: "seven tee",
    80: "eigh tee",
    90: "nine tee",
}

#%%
SPANISH_MARKERS = {
    "el", "la", "los", "las", "un", "una", "de", "que", "y", "en",
    "para", "por", "con", "es", "son", "tienes", "primero", "luego",
    "dividir", "número", "números", "resultado", "porque", "obtener",
    "hola", "claro", "sí"
}

ENGLISH_MARKERS = {
    "the", "a", "an", "and", "or", "to", "of", "in", "for", "with",
    "is", "are", "you", "first", "then", "divide", "number", "numbers",
    "result", "because", "get", "hello", "sure"
}

CHINESE_MARKERS = {
    "的", "了", "是", "我", "你", "他", "她", "它", "我们", "你们", "他们",
    "这", "那", "这里", "那里", "这个", "那个",
    "在", "有", "和", "跟", "与", "或", "也", "就", "都",
    "不", "没有", "很", "非常", "可以", "能", "会", "要", "想",
    "请", "谢谢", "你好", "好的", "当然",
    "因为", "所以", "如果", "然后", "先", "再",
    "什么", "怎么", "为什么", "多少", "哪里", "谁",
    "数字", "号码", "结果", "得到", "除以", "加", "减", "乘", "等于",
}

#%% 
LANGUAGE_NAME = {
    'en': "English",
    'zh': "Chinese",
    'de': "German",
    'es': "Spanish",
    'ru': "Russian",
    'ko': "Korean",
    'fr': "French",
    'ja': "Japanese",
    'pt': "Portuguese",
    'tr': "Turkish",
    'pl': "Polish",
    'ca': "Catalan",
    'nl': "Dutch",
    'ar': "Arabic",
    'sv': "Swedish",
    'it': "Italian",
    'id': "Indonesian",
    'hi': "Hindi",
    'fi': "Finnish",
    'vi': "Vietnamese",
    'he': "Hebrew",
    'uk': "Ukrainian",
    'el': "Greek",
    'ms': "Malay",
    'cs': "Czech",
    'ro': "Romanian",
    'da': "Danish",
    'hu': "Hungarian",
    'ta': "Tamil",
    'no': "Norwegian",
    'th': "Thai",
    'ur': "Urdu",
    'hr': "Croatian",
    'bg': "Bulgarian",
    'lt': "Lithuanian",
    'la': "Latin",
    'mi': "Maori",
    'ml': "Malayalam",
    'cy': "Welsh",
    'sk': "Slovak",
    'te': "Telugu",
    'fa': "Persian",
    'lv': "Latvian",
    'bn': "Bengali",
    'sr': "Serbian",
    'az': "Azerbaijani",
    'sl': "Slovenian",
    'kn': "Kannada",
    'et': "Estonian",
    'mk': "Macedonian",
    'br': "Breton",
    'eu': "Basque",
    'is': "Icelandic",
    'hy': "Armenian",
    'ne': "Nepali",
    'mn': "Mongolian",
    'bs': "Bosnian",
    'kk': "Kazakh",
    'sq': "Albanian",
    'sw': "Swahili",
    'gl': "Galician",
    'mr': "Marathi",
    'pa': "Punjabi",
    'si': "Sinhala",
    'km': "Khmer",
    'sn': "Shona",
    'yo': "Yoruba",
    'so': "Somali",
    'af': "Afrikaans",
    'oc': "Occitan",
    'ka': "Georgian",
    'be': "Belarusian",
    'tg': "Tajik",
    'sd': "Sindhi",
    'gu': "Gujarati",
    'am': "Amharic",
    'yi': "Yiddish",
    'lo': "Lao",
    'uz': "Uzbek",
    'fo': "Faroese",
    'ht': "Haitian Creole",
    'ps': "Pashto",
    'tk': "Turkmen",
    'nn': "Nynorsk",
    'mt': "Maltese",
    'sa': "Sanskrit",
    'lb': "Luxembourgish",
    'my': "Myanmar",
    'bo': "Tibetan",
    'tl': "Tagalog",
    'mg': "Malagasy",
    'as': "Assamese",
    'tt': "Tatar",
    'haw': "Hawaiian",
    'ln': "Lingala",
    'ha': "Hausa",
    'ba': "Bashkir",
    'jw': "Javanese",
    'su': "Sundanese"
}

BASE_CURSE_PATTERNS = [
	# English
	r"\bass(?:hole)?s?\b",
	r"\bbastards?\b",
	r"\bbitch(?:es)?\b",
	r"\bbullshit\b",
	r"\bcocks?\b",
	r"\bcrap\b",
	r"\bcunts?\b",
	r"\bdamn\b",
	r"\bdick(?:head)?s?\b",
	r"\bdildos?\b",
	r"\bdipshits?\b",
	r"\bfag(?:got)?s?\b",
	r"\bfuck(?:er|ed|ing|s)?\b",
	r"\bcoons?\b",
	r"\bhoes?\b",
	r"\bkikes?\b",
	r"\bgoddamn\b",
	r"\bhell\b",
	r"\bjackass(?:es)?\b",
	r"\bmotherfuckers?\b",
	r"\bnigg(?:a|er)s?\b",
	r"\bpiss(?:ed|ing)?\b",
	r"\bpricks?\b",
	r"\bpuss(?:y|ies)\b",
	r"\bshit(?:ty|head|s|show)?\b",
	r"\bsluts?\b",
	r"\bson of a bitch\b",
	r"\btwats?\b",
	r"\bwankers?\b",
	r"\bwhores?\b",

	# Spanish
	r"\bputas?\b",
	r"\bputos?\b",
	r"\bmierda\b",
	r"\bcarajo\b",
	r"\bcoño\b",
	r"\bcojones?\b",
	r"\bjoder\b",
	r"\bjod(?:e|er|ido|ida|iendo|es)\b",
	r"\bpendej(?:o|a|os|as)\b",
	r"\bcabr[oó]n(?:es)?\b",
	r"\bcabronas?\b",
	r"\bculo\b",
	r"\bculos\b",
	r"\bgilipollas\b",
	r"\bimb[eé]cil(?:es)?\b",
	r"\bidiotas?\b",
	r"\bmam[aá]huevos?\b",
	r"\bmaric[oó]n(?:es)?\b",
	r"\bverga\b",
	r"\bpinche\b",
	r"\bching(?:a|ar|ado|ada|ados|adas|ando|as)\b",
	r"\bchingaderas?\b",
	r"\bhij(?:a|as|o|os) de put(?:a|as|o|os)\b",
	r"\bno mames\b",
	r"\bmam[oó]n(?:es)?\b",
	r"\bzorras?\b",
	r"\bperras?\b",
]

#%% 